# Generated by Django 3.2.11 on 2022-01-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220111_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Phone number'),
        ),
    ]
