# Generated by Django 3.2.11 on 2022-01-11 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='Client')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('phoneNumber', models.CharField(max_length=9, verbose_name='Phone number')),
                ('category', models.CharField(max_length=100, verbose_name='Category/Type')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Creation')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('taken', models.BooleanField(default=False, verbose_name='Taken')),
            ],
        ),
    ]
