# Generated by Django 3.2.11 on 2022-01-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='phoneNumber',
            field=models.CharField(max_length=50, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='zipcode',
            field=models.CharField(max_length=25, verbose_name='Zip Code'),
        ),
    ]
