# Generated by Django 3.2.11 on 2022-01-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20220111_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Date'),
        ),
    ]
