# Generated by Django 3.2.11 on 2022-01-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='number_billing',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Number billing'),
        ),
    ]
